#!/usr/bin/env python3

import sys, os

if len(sys.argv) != 3:
	print('Usage:\n prog-get install progname')
else:
	progname = sys.argv[2]
	os.system('git clone https://josimarneto@' + \
	'github.com/josimarneto/' + progname + '.git ' + \
	'___temp___protemp_dir___/')
	os.system('mv ___temp___protemp_dir___/' + progname + \
	' /usr/bin/' + progname)
	os.system('chmod 777 /usr/bin/' + progname)
	os.system('rm -r ___temp___protemp_dir___/')
